# Generated by Django 3.2 on 2022-08-09 21:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('phone_nmber', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=300, null=True)),
                ('elect_number', models.CharField(blank=True, max_length=300, null=True)),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('invoice_owner', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('remaining_amount', models.IntegerField(default=0)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.apartment')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.building'),
        ),
    ]
