# Generated by Django 3.2.15 on 2023-04-02 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='invoice_owner_allowed',
            field=models.ManyToManyField(blank=True, to='app.invoice_owner'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='type_of_user',
            field=models.CharField(choices=[('d', 'Default'), ('v', 'View Only')], default='d', max_length=20),
        ),
        migrations.CreateModel(
            name='maintenance_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('today_date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.apartment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.invoice_owner')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
