# Generated by Django 3.2.15 on 2023-04-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230402_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='temp_del',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='temp_del_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
