# Generated by Django 3.2 on 2022-08-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_invoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='type_of',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
