# Generated by Django 3.2 on 2022-08-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_apartment_type_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
