# Generated by Django 3.2.15 on 2023-05-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230418_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='delete_report_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='download_report_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
