# Generated by Django 3.2 on 2022-08-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220820_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='invoice_owner',
        ),
    ]
