# Generated by Django 3.2.15 on 2023-06-25 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230626_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='recieved_by',
            new_name='received_by',
        ),
    ]
