# Generated by Django 3.2.15 on 2023-06-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_recieved_by_invoice_received_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='prev_tenants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='curr_tenant',
            field=models.CharField(blank=True, default='default', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.CharField(blank=True, default='default', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_invoice',
            name='tenant',
            field=models.CharField(blank=True, default='default', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenant_hist',
            field=models.ManyToManyField(to='app.prev_tenants'),
        ),
    ]
