# Generated by Django 3.2.15 on 2023-06-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20230626_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenance_invoice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
