# Generated by Django 3.2.15 on 2023-07-01 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20230701_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='aprt_tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('phone_number', models.IntegerField(default=0)),
                ('electric_number', models.IntegerField(default=0)),
                ('contract_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.aprt_tenant'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenant_hist',
            field=models.ManyToManyField(related_name='tenant_history', to='app.aprt_tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.aprt_tenant'),
        ),
        migrations.AddField(
            model_name='maintenance_invoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.aprt_tenant'),
        ),
    ]
