# Generated by Django 3.2.15 on 2023-07-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20230701_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='tenant_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='tenant_hist',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='maintenance_invoice',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='aprt_tenant',
        ),
        migrations.AddField(
            model_name='tenant_link',
            name='apartments',
            field=models.ManyToManyField(to='app.apartment'),
        ),
    ]
