# Generated by Django 3.2.15 on 2023-07-07 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20230708_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='aprt_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tenant_link'),
        ),
    ]
