# Generated by Django 3.0.6 on 2024-03-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20230730_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='annual_rent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
