# Generated by Django 3.0.6 on 2024-09-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20240310_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='delete_invoice_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='download_report_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
