# Generated by Django 3.0.6 on 2024-09-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20240927_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='other_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
