# Generated by Django 3.0.6 on 2024-11-16 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_user_tasks_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_tasks',
            old_name='last_updated',
            new_name='last_updated_at',
        ),
        migrations.RenameField(
            model_name='user_tasks_log',
            old_name='last_updated',
            new_name='last_updated_at',
        ),
    ]
