# Generated by Django 3.0.6 on 2024-11-16 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20241116_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_tasks_log',
            name='task',
        ),
        migrations.RemoveField(
            model_name='user_tasks_log',
            name='user',
        ),
        migrations.DeleteModel(
            name='user_tasks',
        ),
        migrations.DeleteModel(
            name='user_tasks_log',
        ),
    ]
