# Generated by Django 3.0.6 on 2024-11-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_user_tasks_user_tasks_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tasks_log',
            name='note',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='user_tasks',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_tasks_log',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
