# Generated by Django 3.0.6 on 2024-11-16 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20241116_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_tasks_log',
            old_name='last_updated_at',
            new_name='added_at',
        ),
    ]
