# Generated by Django 3.0.6 on 2024-11-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20241116_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tasks_log',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
    ]
