# Generated by Django 3.0.6 on 2024-11-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_user_tasks_log_is_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_tasks',
            name='completion',
        ),
    ]
